### ISSUE TITLE
compare clean data and standard data

### ISSUE THREAD

**Issue by alvizek** [SRJPE/jpe-clear-adult-edi#3]
Same comment as Battle - double check the clean clear data with the standard data to make sure important variables werent excluded

**Comment by liz-fw** [comment]
columns that I think we could include:
- `ucc_relate`
- `picket_weir_location`, `picket_weir_relation`
- `redd_loc`
- `gravel`, `inj_site`
- `pre_redd_depth`, `redd_pit_depth`, `redd_tail_depth`
- `start_60`, `end_60`, `sec_60`
- `start_80`, `end_80`, `secs_80`
- `bombvel_60`, `bombvel_80`

To confirm:
- Is it too much location data to have the picket weir/ucc_relate columns? 
- Would the 60 and 80 bomb velocity fields be helpful for a study?
